exports.PRODUCTION_SERVER_URI = 'https://shrek-tech.herokuapp.com'
exports.PRODUCTION_CLIENT_URI = 'https://61757bc4e2d4e2d56c38c281--shrek-tech.netlify.app'
exports.DEV_CLIENT_URI = 'http://localhost:8080'
exports.DEV_SERVER_URI = 'http://localhost:8000'
exports.DEV_SOCKET_URI = 'http://localhost:4000'
