name: Node.js CI

on:
  pull_request:
    branches: [main]

jobs:
  lint-client:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 16.x for client
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
          cache-dependency-path: "client/package-lock.json"
      - name: Install client dependencies
        run: npm install
      - name: Lint client
        run: npm run lint

  lint-test-server:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 16.x for server
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
          cache-dependency-path: "server/package-lock.json"
      - name: Install server dependencies
        run: npm install
      - name: Lint server
        run: npm run lint
      - name: Create Mongo Docker container
        uses: DigiPie/mongo-action@v1.0.1
        with:
          image-version: latest
          port: 27017
      - name: Import test data to Mongo
        run: |
          sudo mongo localhost:27017
          mongoimport --uri mongodb://localhost:27017 --db project3219 --collection users --file ./test/data/mockUserData.json --jsonArray
          mongoimport --uri mongodb://localhost:27017 --db project3219 --collection codingquestions --file ./test/data/mockCodingQuestionData.json --jsonArray
          mongoimport --uri mongodb://localhost:27017 --db project3219 --collection interviewquestions --file ./test/data/mockInterviewQuestionData.json --jsonArray
      - name: Create .env
        run: |
          touch .env
          echo MONGO_URI_TEST=mongodb://localhost:27017/project3219 >> .env
          echo JWT_SECRET_KEY=testSecretKey >> .env
          echo JWT_TEST=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImthaWVuLmZvb0BnbWFpbC5jb20iLCJ1c2VySWQiOiI2MTgxM2RiOTAzMzZmNjVmYzcwM2FjNzkiLCJ1c2VybmFtZSI6Indha3UiLCJpYXQiOjE2MzU5MTczNTh9.xntZCvnqqPxRvrRuhXDX04kgJnirLeSbAUMb2Ly77wo >> .env
          echo JWT_BLACKLIST_TEST=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBlZXJQcmVwMkBnbWFpbC5jb20iLCJ1c2VySWQiOiI2MTg1MjcxOWFhYjExNDI3ZWY3YzM0ZWEiLCJ1c2VybmFtZSI6InNocmVrVGVjaCIsImlhdCI6MTYzNjExNjI2OX0.aOK50ZzUrd2GVJ-trP4gjnQcAbVQH-IOWhLXFq6e4DM >> .env
      - name: Test server
        run: npm test
