name: Node.js CI

on:
  pull_request:
    branches: [main]

jobs:
  lint-client:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 16.x for client
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
          cache-dependency-path: "client/package-lock.json"
      - name: Install client dependencies
        run: npm install
      - name: Lint client
        run: npm run lint

  lint-test-server:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 16.x for server
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
          cache-dependency-path: "server/package-lock.json"
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: 4.0
      - name: Create .env
        run: |
          touch .env
          echo MONGO_URI=${{ secrets.MONGO_URI }} >> .env
      - name: Install server dependencies
        run: npm install
      - name: Lint server
        run: npm run lint
      - name: Test server
        run: npm test
