name: Node.js CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test-server:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
          cache-dependency-path: "server/package-lock.json"
      - run: npm install
      - run: npm test
      - run: npm run lint

  lint-build-client:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
          cache-dependency-path: "client/package-lock.json"
      - run: npm install
      - run: npm run lint
      - name: Build static files
        run: npm run build

  copy-static-files:
    needs: lint-build-client
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Copy client static files to server
        uses: canastro/copy-file-action@master
        with:
          source: "client/dist"
          target: "server/dist"

  deploy:
    needs: [lint-test-server, copy-static-files]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "shrektech"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
